-- Add structured_insights column to profile_snapshots for storing rich,
-- structured JSON data generated by the Profile agent.
-- Nullable for backward compatibility with existing snapshots.
ALTER TABLE profile_snapshots ADD COLUMN structured_insights TEXT;
